version: '3.1'
services:
  postgres-db:
    image: postgres:12.3
    container_name: postgres-db
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
  leocode-backend:
    image: leocode-backend
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.multistage
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres-db:5432/db
    ports:
      - "9090:9090"
    depends_on:
      - postgres-db
  leocode-testing-api:
    image: leocode-testing-api
    build:
      context: ./testing-api
      dockerfile: src/main/docker/Dockerfile.multistage
    ports:
      - "8080:8080"
    depends_on:
      - leocode-backend
